  steps:
  - name: gradle:8-jdk21
    entrypoint: gradle
    args: ['--version']
  - name: gradle:8-jdk21
    entrypoint: gradle
    args: ['test']
  - name: gradle:8-jdk21
    entrypoint: gradle
    args: ['assemble']
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members", "--build-arg=JAR_FILE=build/libs/members-0.0.1-SNAPSHOT.jar", "."]
  images: ["us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members"]
  - name: google/cloud-sdk
    args: ['gcloud', 'deploy', 'releases', 'create', 'member-release-${SHORT_SHA}',
         '--image', 'us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members@sha256:27f9732dac52f7e1d5bf2800e6e05806567dd53fcbf033f9de4cbb99b180abb2',
         '--region', 'us-central1'
         ]