steps:
#Testing
- name: 'gradle:8-jdk21' 
  entrypoint: 'gradle'
  args: ['test']
#Gradle build
- name: 'gradle:8-jdk21' 
  entrypoint: 'gradle'
  args: ['assemble']
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/daisyduck-reborn/members:${COMMIT_SHA}',
   '-t', 
   'gcr.io/daisyduck-reborn/members:latest',
   '.'
  ]
# push images to Google Container Registry with tags
images: [
   'gcr.io/daisyduck-reborn/members:${COMMIT_SHA}',
   'gcr.io/daisyduck-reborn/members:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY