steps:
#Testing
- name: 'gradle:8-jdk21' 
  entrypoint: 'gradle'
  args: ['test']
#Gradle build
- name: 'gradle:8-jdk21' 
  entrypoint: 'gradle'
  args: ['assemble']
#Docker Build
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/daisyduck-reborn/members:${COMMIT_SHA}',
   '-t', 
   'gcr.io/daisyduck-reborn/members:latest',
   '.'
  ]
#Create Release
- name: 'google/cloud-sdk'
  args: ['gcloud', 'deploy', 'releases', 'create', 'member-release-${SHORT_SHA}',
        '--images', 'image1=us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members',
        '--region', 'us-central1',
        '--delivery-pipeline', 'members-delivery-pipeline',
        '--from-k8s-manifest', 'config/stag/application.deployment.yaml',
        '--source', 'members'
        ]

# push images to Google Container Registry with tags
images: [
   'gcr.io/daisyduck-reborn/members:${COMMIT_SHA}',
   'gcr.io/daisyduck-reborn/members:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY