steps:
- name: gradle:8-jdk21
  entrypoint: gradle
  args: ['--version']
- name: gradle:8-jdk21
  entrypoint: gradle
  args: ['test']
- name: gradle:8-jdk21
  entrypoint: gradle
  args: ['assemble']
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members:${COMMIT_SHA}", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members:${COMMIT_SHA}']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "member-release-${REVISION_ID}",
      "--delivery-pipeline", "members-delivery-pipeline",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "image1=us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members:${COMMIT_SHA}"
    ]
images: ["us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members:${COMMIT_SHA}"]
options:
  logging: CLOUD_LOGGING_ONLY