steps:
options:
  logging: CLOUD_LOGGING_ONLY
- name: gradle:8-jdk21
  entrypoint: gradle
  args: ['--version']
- name: gradle:8-jdk21
  entrypoint: gradle
  args: ['test']
- name: gradle:8-jdk21
  entrypoint: gradle
  args: ['assemble']
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members", "."]  
- name: google/cloud-sdk
  args: ['gcloud', 'deploy', 'releases', 'create', 'member-release-${SHORT_SHA}',
        '--images', 'image1=us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members',
        '--region', 'us-central1',
        '--delivery-pipeline', 'members-delivery-pipeline',
        '--source', 'members'
        ]
images: ["us-central1-docker.pkg.dev/daisyduck-reborn/daisyduck-repo/members"]