apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: members
build:
  artifacts:
    - image: members
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - config/dev/application.deployment.yaml
